backend:
  name: github
  repo: jaredGuzman/skyborn
  branch: main
  base_url: https://sveltia-cms-auth.skybornstudios-devs.workers.dev

media_folder: public/image/uploads # Location where files will be stored in the repo

collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    label_singular: 'Post'
    folder: 'src/content/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: # The fields for each document, usually in frontmatter
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Slug',
          name: 'slug',
          widget: 'string',
          pattern: ['^[a-zA-Z0-9-]+$', 'Must contain only letters, numbers, and hyphens'],
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD HH:mm', default: '{{now}}' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - {
          label: 'Excerpt',
          name: 'excerpt',
          widget: 'text',
          required: false,
          hint: 'Optional: Override the auto-generated excerpt with a custom one',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
